# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iOSNote' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry'
  pod 'MBProgressHUD'


   # Pods for iOSNote

  target 'iOSNoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSNoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
